name: Deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: generated
      - name: Merge main  
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git fetch
          git checkout main
          git checkout generated
          git checkout origin/main -- source/_posts
          git checkout origin/main -- source/images
          git checkout origin/main -- themes
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install NPM Modules
        run: |
          npm install --force
      - name: Delete docs
        run: |
          sudo rm -r docs/
      - name: Clean
        uses: heowc/action-hexo@main
        with:
          args: clean
      - name: Generate
        uses: heowc/action-hexo@main
        with:
          args: generate
      - name: Generate CNAME
        run: |
          echo 0x00000000.dev > CNAME
          echo "0x00000000.dev" | sudo tee docs/CNAME
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add * -f
          git commit -m "Generated 0x00000000.dev site."
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: generated
          force: true
